server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: spectra-demo-api
  
logging:
  level:
    com.spectra.demo: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 